src/snek5000/assets/default_configfile.yml
src/snek5000/output/base.py

Check configfile existence early.
Fixes #2

Add asset default_configfile.yml to fallback

---

.github/workflows/tests.yml
CHANGELOG.md
setup.cfg
src/snek5000/__init__.py
src/snek5000/operators.py
src/snek5000/output/base.py
src/snek5000/output/print_stdout.py
src/snek5000/solvers/base.py
src/snek5000/util/__init__.py
tests/conftest.py
tests/test_oper.py
tests/test_params.py

- output:
- name_pkg -> name_solver
- post_init
- params.xml -> params_simul.xml

Fluidsim core changes for Output API

---

docs/Makefile
setup.cfg
src/snek5000/__init__.py
tests/conftest.py

Require fluidsim-core 0.4.1

---

.pre-commit-config.yaml
docs/packaging.rst
setup.cfg
src/snek5000/__init__.py
src/snek5000/assets/__init__.py
src/snek5000/assets/compiler.smk
src/snek5000/assets/internal.smk
src/snek5000/assets/io.smk
src/snek5000/assets/nek5000.smk
src/snek5000/output/base.py
src/snek5000/util/__init__.py
src/snek5000/util/archive.py
src/snek5000/util/smake.py
tests/conftest.py
tests/test_util.py

Snakemake version 6.1.1 and modules

---

.github/workflows/tests.yml

Hopefully safer from future incidents

Swap codecov-action with Python package

---

src/snek5000/output/base.py
src/snek5000/solvers/kth.py

Fix bug when name_solver not equal to package

---

src/snek5000/__init__.py
src/snek5000/solvers/base.py

Fix https://github.com/exabl/snek5000-cbox/issues/1 (with https://github.com/exabl/snek5000-cbox/commit/a2d0aafafbff57cd70e047154fbc73adeedc5971)

Fix info solver

---

CHANGELOG.md
src/snek5000/assets/SIZE.j2
src/snek5000/operators.py

Remove parameter oper.max.order_time which is now a property

---

activate.sh
docs/Makefile
docs/conf.py
docs/configuring.rst
docs/nek5000.rst
docs/packaging.rst
docs/tutorials.rst
setup.cfg
src/snek5000/output/base.py
tests/test_config.py

- Local config file at XDG_CONFIG_HOME
- Environment variable override possibility
Fixes #47

Config alternate paths and environment sensitive

---

docs/packaging.rst
src/snek5000/solvers/kth.py

_complete_params_with_default should be a class method to allow for solving temperature

---

setup.cfg

Requires python>=3.8, fluidsim-core>=0.5.0, pymech>=1.4.1

---

docs/packaging.rst
src/snek5000/output/base.py

Support usr.f file in source

---

docs/conf.py
docs/examples/snek5000-tgv/LICENSE
docs/examples/snek5000-tgv/README.md
docs/examples/snek5000-tgv/setup.cfg
docs/examples/snek5000-tgv/setup.py
docs/examples/snek5000-tgv/src/snek5000_tgv/Snakefile
docs/examples/snek5000-tgv/src/snek5000_tgv/output.py
docs/examples/snek5000-tgv/src/snek5000_tgv/solver.py
docs/examples/snek5000-tgv/src/snek5000_tgv/templates/__init__.py
docs/examples/snek5000-tgv/src/snek5000_tgv/tgv.par.cfg
docs/examples/snek5000-tgv/src/snek5000_tgv/tgv.usr.f
docs/ipynb/executed/tuto_load_print_stdout.ipynb
docs/tutorials.rst
src/snek5000/__init__.py
src/snek5000/output/base.py
src/snek5000/util/files.py
src/snek5000/util/restart.py
tests/test_restart.py

Add reader parameter to snek5000.load and docs

---

CHANGELOG.md
docs/examples/snek5000-canonical/src/snek5000_canonical/Snakefile
docs/examples/snek5000-canonical/src/snek5000_canonical/__init__.py
docs/examples/snek5000-canonical/src/snek5000_canonical/output.py
docs/examples/snek5000-canonical/src/snek5000_canonical/solver.py
docs/examples/snek5000-tgv/src/snek5000_tgv/Snakefile
docs/examples/snek5000-tgv/src/snek5000_tgv/__init__.py
docs/examples/snek5000-tgv/src/snek5000_tgv/output.py
docs/examples/snek5000-tgv/src/snek5000_tgv/templates/__init__.py
docs/packaging.rst
src/snek5000/__init__.py
src/snek5000/assets/compiler.smk
src/snek5000/assets/internal.smk
src/snek5000/assets/io.smk
src/snek5000/make.py
src/snek5000/output/base.py
src/snek5000/output/phys_fields.py
src/snek5000/util/__init__.py
src/snek5000/util/smake.py
tests/test_resources.py

I had to change few things to try to better understand some snek internals.
I propose to depreciate the function `source_root` and to rename it as `get_nek_source_root`.

Improve a bit internal and public API

---

docs/configuring.rst
src/snek5000/output/base.py
src/snek5000/util/__init__.py
tests/test_config.py

Config file snek5000.yml

---

src/snek5000/__init__.py
src/snek5000/params.py

I guess we should support 
```python
from snek5000 import load_params
```

Add load_params to the module snek5000

---

.pre-commit-config.yaml
docs/install.rst
docs/ipynb/executed/tuto_simul_exec.ipynb
src/snek5000/make.py
tests/test_make.py

- Upgrade pre-commit hooks and add mdformat
- Update docs on Snakemake API
- Note on Nek5000 dependencies
- Set force_incomplete for retry after Nek5000 build failures, truly parallel test

Docs and improved first-time installation

---

src/snek5000/output/print_stdout.py
tests/test_cbox.py

Read print stdout as dataframe

---

README.md
docs/examples/scripts/simul_tgv_short.py
docs/index.rst

Doc readme

---

docs/conf.py
docs/how-to/history_points.md
docs/how-to/index.md
docs/index.rst
noxfile.py
requirements/docs.txt
setup.cfg
src/snek5000/output/history_points.py

See #142
- Empty how-to index page
- Nox session docs-autobuild
- Ensure sphinx and sphinx-autobuild are from venv
- How to history points

How-to page and how to history points

---

docs/tuto_cbox.md
docs/tuto_phill.md
docs/tuto_phill_setup.md
docs/tuto_tgv.md
setup.cfg
src/snek5000/util/__init__.py
src/snek5000/util/console.py
tests/test_console.py

Minimalist snek5000-info...
Fixes #159

snek5000-info console script

---

src/snek5000/log.py
tests/test_config.py

Not adding handler when rich is not installed

---

docs/conf.py
docs/examples/scripts/tuto_cbox.py
docs/examples/scripts/tuto_phill.py
docs/examples/scripts/tuto_tgv.py
src/snek5000/make.py
tests/conftest.py
tests/test_config.py

Support sim.make.exec("run_fg", nproc=2)

---

src/snek5000/operators.py
tests/test_oper/test_box_2d.box
tests/test_oper/test_box_template.box

Improve comments in .box file

---

.github/workflows/tests.yml
pyproject.toml

Generate coverage XML report

---

docs/conf.py
docs/tuto_cbox.md
docs/tuto_phill.md
docs/tuto_tgv.md
requirements/docs.txt
requirements/vcs_packages.in

Improve tuto_phill with load/plot of hexa data

---

docs/conf.py
docs/tuto_cbox.md
docs/tuto_phill.md
docs/tuto_phill_setup.md
docs/tuto_tgv.md
setup.cfg

Rename console scripts

---

docs/examples/scripts/tuto_cbox.py
docs/examples/scripts/tuto_phill.py
docs/tuto_cbox.md
src/snek5000/output/history_points.py

Improve tuto cbox

---

Makefile
pyproject.toml
setup.cfg
src/snek5000/clusters.py
src/snek5000/make.py
tests/test_make.py

snek-make command

---

src/snek5000/util/console.py

Fluidsim to snek5000 in load

---

docs/release.md

Update release process (from Pymech)

---

src/snek5000/solvers/base.py
src/snek5000/util/restart.py
tests/conftest.py
tests/test_restart.py

Refactor load_for_restart to support new_dir_results=True

---

.pre-commit-config.yaml
docs/dev/release.md
docs/examples/snek5000-canonical/README.md
docs/how-to/edit_tutorials.md
docs/how-to/history_points.md
docs/how-to/index.md
docs/how-to/restart.md
docs/tuto_tgv.md

Improve documentation on restart

---

requirements/dev.txt
requirements/docs.txt
requirements/main.txt
requirements/tests-editable.txt
requirements/tests.txt
requirements/vcs_packages.in
setup.cfg

Use fluidsim-core 0.7.1

---

src/snek5000/util/files.py

Use read_header(self.path).time instead of readnek(self.path).time

---

docs/examples/scripts/tuto_tgv.py
docs/examples/snek5000-tgv/src/snek5000_tgv/output.py
docs/examples/snek5000-tgv/src/snek5000_tgv/solver.py
docs/examples/snek5000-tgv/src/snek5000_tgv/tgv.usr.f
docs/tuto_tgv.myst.md
src/snek5000/output/__init__.py
src/snek5000/output/spatial_means.py
src/snek5000/util/console.py
tests/conftest.py
tests/test_tgv.py

First step spatial_means

---

src/snek5000/resources/SIZE.j2

Add block user_size in resources/SIZE.j2

---

tests/conftest.py
tests/test_restart_command.py

Test HAS_TO_SAVE and NEW_DIR_RESULTS with a readonly simulation directory

---

CONTRIBUTING.md
docs/dev/edit_tutorials.md
docs/dev/howto_doc.md
docs/dev/howto_test.md
docs/dev/index.rst
docs/dev/release.md
docs/how-to/templates.md

Improve documentation for developers

---

src/snek5000/operators.py
src/snek5000/output/base.py
src/snek5000/resources/__init__.py

See https://github.com/Nek5000/NekDoc/pull/133/files

Fix documention after changes in Nek doc (ref tools_genbox)

---

docs/examples/snek5000-tgv/src/snek5000_tgv/output.py
docs/examples/snek5000-tgv/src/snek5000_tgv/tgv.usr.f
src/snek5000/output/remaining_clock_time.py
src/snek5000/output/simple_csv.py
src/snek5000/output/spatial_means.py
tests/conftest.py
tests/test_oper/test_size_template.f
tests/test_tgv.py

Remaining clock time output for TGV solver.

---

requirements/dev.txt
requirements/docs.txt
requirements/main.txt
requirements/tests-editable.txt
requirements/tests.txt

Bump gitpython from 3.1.29 to 3.1.30 in requirements

---

docs/how-to/config-c-fortran-compilers.md
docs/how-to/index.md
docs/tuto_config.rst

How to configure C and Fortran compilers

---

CHANGELOG.md
setup.cfg
src/snek5000/make.py
tests/test_make.py

Fixes #179
Manual intervention but this should do it. Normally solves:
```py
RuntimeError("Nek5000 build failed.")
```

New snek-make-nek command

---

docs/joss_paper/paper.bib

See https://github.com/openjournals/joss-reviews/issues/5433#issuecomment-1533113189

joss_paper: add missing doi

---

docs/install.rst

Note Nek5000 version requirements

---

docs/joss_paper/paper.bib
docs/joss_paper/paper.md

I've made some minor edits to the JOSS paper before accepting

Edits for JOSS paper
